#!/usr/bin/env bash
set -euo pipefail
# Purpose: export local virtual keys as env vars for notebook runtime.
# Called by: dev container startup before Jupyter launch.
# Notes: converts keys.local.json entries into shell exports.

KEYS_FILE="${KEYS_FILE:-/workspace/compose-state/keys/keys.local.json}"
DEV_SECRETS_ENV_FILE="${DEV_SECRETS_ENV_FILE:-/tmp/dev-secrets.env.sh}"
DEV_KEYS_STRICT="${DEV_KEYS_STRICT:-1}"

python3 - <<'PY'
import json
import os
import pathlib
import shlex
import sys

keys_path = pathlib.Path(os.environ.get("KEYS_FILE", ""))
env_file = pathlib.Path(os.environ.get("DEV_SECRETS_ENV_FILE", "/tmp/dev-secrets.env.sh"))
strict = os.environ.get("DEV_KEYS_STRICT", "1").lower() not in {"0", "false", "no"}

if not keys_path.is_file():
    if strict:
        print(f"ERROR: KEYS_FILE missing: {keys_path}", file=sys.stderr)
        sys.exit(1)
    env_file.write_text("# generated: no keys file found\n")
    print(f"WARN: KEYS_FILE missing, wrote empty env file: {keys_path}", file=sys.stderr)
    sys.exit(0)

try:
    payload = json.loads(keys_path.read_text())
except Exception as exc:
    print(f"ERROR: failed to parse {keys_path}: {exc}", file=sys.stderr)
    sys.exit(1)

entries = payload.get("keys", [])
if not isinstance(entries, list):
    print("ERROR: keys.local.json must contain a 'keys' list", file=sys.stderr)
    sys.exit(1)

key_by_name: dict[str, str] = {}
for item in entries:
    if not isinstance(item, dict):
        continue
    name = str(item.get("name", "")).strip()
    token = str(item.get("token", "")).strip()
    if name and token:
        key_by_name[name] = token

required = ("dev", "stage", "prod", "user1", "user2")
missing = [name for name in required if name not in key_by_name]
if strict and missing:
    print(f"ERROR: missing required virtual keys in {keys_path}: {', '.join(missing)}", file=sys.stderr)
    sys.exit(1)

lines = [
    "# generated by export-dev-secrets-env.sh",
]

for name, env_name in (
    ("dev", "MODEL_API_KEY_DEV"),
    ("stage", "MODEL_API_KEY_STAGE"),
    ("prod", "MODEL_API_KEY_PROD"),
    ("user1", "MODEL_API_KEY_USER1"),
    ("user2", "MODEL_API_KEY_USER2"),
):
    lines.append(f"export {env_name}=" + shlex.quote(key_by_name.get(name, "")))

env_file.write_text("\n".join(lines) + "\n")
print(f"Generated notebook secret env file at {env_file}")
PY
