#!/usr/bin/env bash
set -euo pipefail

echo "== Manual Review Definition =="
echo ""
echo "Scope:"
echo "- Review the current working tree changes."
echo "- Decide if the change is commit-ready."
echo ""
echo "Steps:"
echo "1) Inspect change scope"
echo "   - git status --short"
echo "   - git diff --stat"
echo ""
echo "2) Review content"
echo "   - Findings by severity: High, Medium, Low"
echo "   - Open questions/assumptions"
echo "   - Test gap or residual risk"
echo ""
echo "3) Decide auto-doc updates"
echo "   - ADR raw log decision:"
echo "     add/update/skip -> docs/auto-doc/adr/raw-log.md"
echo "   - User value log decision:"
echo "     add/update/skip -> docs/auto-doc/value/user-value-log.md"
echo ""
echo "4) Commit readiness gate"
echo "   - findings_resolved: yes/no"
echo "   - doc_decisions_made: yes/no"
echo "   - ready_to_commit: yes/no"
echo ""
echo "Definition of Done:"
echo "- At least one review finding (or explicit 'no issues found')."
echo "- Auto-doc decision recorded for both logs (add/update/skip)."
echo "- Explicit commit readiness decision."
echo ""
echo "Current Git Context"
echo "-------------------"
git status --short
echo ""
git diff --stat
